name: Build JAR

on:
  push:
    paths:
      - guac-custom-theme-builder/**
  workflow_dispatch:

jobs:
  build-and-upload-jar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build JAR
      run: |
        cd guac-custom-theme-builder
        jar cfmv branding.jar META-INF/MANIFEST.MF guac-manifest.json css images translations META-INF
        mv branding.jar ../

    - name: Force add and Commit JAR to Root Directory
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -f branding.jar
        git status
        git commit -m "Update branding.jar" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
